### ISSUE TITLE
Cross-platform support

### ISSUE THREAD

**Issue by Cephlin** [jtomschroeder/cedar#6]
Please make cross-platform. Prioritising UNIX first.

**Comment by beefsack** [comment]
As an Arch user I'd love to see this, but a bit more effort into the issue would be welcome.

Perhaps framing it as a feature instead of a bug; "Cross-platform support" sounds a bit less loaded.

Another option might be to suggest frameworks (GTK, Qt) or existing Rust libraries (gtk-rs, qmlrs etc.) that might assist.

An aside would be it'd probably be valuable to get a second backend in soon as it'll help avoid designing too closely to Cocoa and help achieve ideally a more generic abstraction.

**Comment by jtomschroeder** [comment]
I agree. Cross-platform support is definitely a high priority. I'm going to reframe this as an enhancement (hopefully no one minds). 

The decision to start with `macOS` was merely one of convenience: it's what I know best. I will take a look into the current state of GUI frameworks for rust, maybe prototype some options. If anyone has preferences/suggestions, please share! 

I absolutely agree that this should happen sooner than later in order to avoid coupling to a singular backend.

**Comment by mkeeter** [comment]
For cross-platform support, check out [`libui`](https://github.com/andlabs/libui) (and @pcwalton's Rust bindings [here](https://github.com/pcwalton)).

Both projects seem pretty low-activity at the moment, but in theory this could be a good way to abstract out the platform backends.

**Comment by jtomschroeder** [comment]
Initial cross-platform support added via GTK. Cross-platform support to be considered an on-going priority.

**Comment by beefsack** [comment]
Thanks for your hard work, this is much appreciated by a lot of us in the community.
